/*
 * Copyright (c) 2025, 2026 Boilerplate contributors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package boilerplate.testkit

import munit.ScalaCheckSuite
import org.scalacheck.Arbitrary
import org.scalacheck.Gen

import boilerplate.OpaqueType
import boilerplate.Slice
import boilerplate.TypedError
import boilerplate.UUID
import boilerplate.ValueCodec
import boilerplate.codec.ASCII

final case class KitError(detail: String) extends TypedError(detail, None)

opaque type KitName = String
object KitName extends OpaqueType[KitName, String], OpaqueType.Eq[KitName], OpaqueType.Codec[KitName, String]:
  type Error = KitError
  protected inline def wrap(s: String): KitName = s
  def unwrap(n: KitName): String = n
  protected inline def validate(s: String): Either[KitError, String] =
    if s.isEmpty then Left(KitError("empty")) else Right(ASCII.lower(s))
  inline def apply(inline value: String): KitName = ofUnsafe(value)

class ValueCodecLawsSuite extends ScalaCheckSuite, ValueCodecLaws:

  // Canonical values by construction: generated through the companion's own ofUnsafe.
  private given Arbitrary[KitName] = Arbitrary(Gen.alphaStr.filter(_.nonEmpty).map(KitName.ofUnsafe))

  // 16 generated bytes through v4, so every value is one the constructors actually produce.
  private given Arbitrary[UUID] =
    Arbitrary(Gen.containerOfN[Array, Byte](16, Arbitrary.arbitrary[Byte]).map(bytes => UUID.v4(Slice.of(bytes))))

  valueCodecLaws[Int]("Int")
  valueCodecLaws[Long]("Long")
  valueCodecLaws[Boolean]("Boolean")
  valueCodecLaws[String]("String")
  valueCodecLaws[KitName]("KitName")
  valueCodecNormalisation[KitName]("KitName", Gen.alphaStr)
  valueCodecNormalisation[Int]("Int", Gen.numStr)
  valueCodecRenderWithin[Int]("Int")(c => ASCII.isDigit(c) || c == '-')
  valueCodecRenderWithin[Long]("Long")(c => ASCII.isDigit(c) || c == '-')

  valueCodecLaws[UUID]("UUID")
  valueCodecNormalisation[UUID]("UUID", Gen.uuid.map(_.toString.toUpperCase(java.util.Locale.ROOT)))
  valueCodecRenderWithin[UUID]("UUID")(c => (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || c == '-')

  // The refusal law over the lax spellings each codec must not admit: a leading sign, a
  // neighbouring word, a non-ASCII numeral, and - for UUID - the forms java.util.UUID accepts.
  valueCodecRefuses[Int]("Int", Gen.oneOf("-", "seven", "+1", "\u0664\u0661\u0669"))
  valueCodecRefuses[Long]("Long", Gen.oneOf("-", "seven", "+1", "\u0664\u0661\u0669"))
  valueCodecRefuses[Boolean]("Boolean", Gen.oneOf("yes", "TRUE"))
  valueCodecRefuses[UUID](
    "UUID",
    Gen.oneOf(
      "1-1-1-1-1",
      "+1-1-1-1-1",
      "{017f22e2-79b0-7cc3-98c4-dc0c0c07398f}",
      "urn:uuid:017f22e2-79b0-7cc3-98c4-dc0c0c07398f",
      "017f22e279b07cc398c4dc0c0c07398f"
    )
  )
end ValueCodecLawsSuite
